apiVersion: v2
name: opa
description: An OPA deployment to run alongside applications requiring authorization
type: application
version: 0.1.2
maintainers:
  - name: garryod
    email: "garry.o'donnell@diamond.ac.uk"
