{{ if .Values.opa-authn.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opa-authn
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.arogproj.io
spec:
  project: {{ default .Release.Namespace .Values.project }}
  source:
    repoURL: {{ .Values.opa-authn.repoUrl }}
    targetRevision: {{ .Values.opa-authn.targetRevision }}
    path: {{ .Values.opa-authn.path }}
    {{- if .Values.opa-authn.valuesObject }}
    helm:
      valuesObject:
          {{ .Values.opa-authn.valuesObject | toYaml | nindent 10 }}
    {{- end }}
  destination:
    name: {{ .Values.destination.name }}
    server: {{ .Values.destination.server }}
    namespace: {{ default .Release.Namespace .Values.destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
