name: Policy Container

on:
  workflow_call:

jobs:
  build_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Generate Image Name
        run: echo IMAGE_REPOSITORY=ghcr.io/$(echo "${{ github.repository }}-policy" | tr '[:upper:]' '[:lower:]' | tr '[_]' '[\-]') >> $GITHUB_ENV

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2.2.0
        with:
          version: latest

      - name: Build OPA Policy
        run: >
          opa
          build
          --bundle policy
          --revision ${{ github.ref_name }}
          --ignore *_test.rego

      - name: Setup ORAS
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}
        uses: oras-project/setup-oras@v1

      - name: Publish OPA Bundle
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags') }}
        run: >
          oras
          push
          ${{ env.IMAGE_REPOSITORY }}:${{ github.ref_name }}
          bundle.tar.gz:application/vnd.oci.image.layer.v1.tar+gzip
